### ISSUE TITLE
Dependency pdoc3 has incompatible AGPL license

### ISSUE THREAD

**Issue by lfse-slafleur** [sloisel/streamcapture#3]
Hi again!

Currently pdoc3 is a required dependency however it carries the AGPL license. This dependency is packaged as MIT and is therefore easily integrated in other applications but AGPL has widespread consequences for users of Streamcapture. Therefore, I propose to move pdoc3 to the 'extras' requirements as pdoc3 is not required to run the code but rather as a development tool and so we can keep the MIT license for Streamcapture.

**Comment by sloisel** [comment]
I've merged the thing you said so I guess I'm closing this?

**Comment by lfse-slafleur** [comment]
Thank you for closing the issue, this is perfect!
